services:
  db:
    image: mariadb:11
    container_name: baldo-mariadb
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./data/mysql:/var/lib/mysql

  neo4j:
    image: neo4j:5.15-community
    container_name: baldo-neo4j
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
    volumes:
      - ./data/neo4j:/data

  mongodb:
    image: mongo:7
    container_name: baldo-mongodb
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - ./data/mongo:/data/db

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: baldo-fastapi
    restart: always
    depends_on:
      - neo4j
      - db
      - mongodb
    env_file: .env
    volumes:
      - ./fastapi/logs:/app/logs
    mem_limit: 512m

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baldo-app
    restart: always
    depends_on:
      - db
      - neo4j
      - fastapi
    env_file: .env
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:3001:3002"
    volumes:
      - ./session:/app/server/session
      - ./server/logs:/app/server/logs
      - ./ssl:/app/ssl
      - ./data/planetarium_assets:/app/data/planetarium
      - ./ilpiccolobardo/public:/app/ilpiccolobardo/public
