// Stato condiviso del frontend. Le funzioni dei moduli ne aggiornano i campi.
export const appState = {
    ws: null,
    reconnectInterval: null,
    reconnecting: false,
    selectedAge: null,
    currentStory: null,
    isGenerating: false,
    generationTimer: null,
    speechSynthesis: window.speechSynthesis,
    favorites: [],
    favoritesReadable: true,
    isNightMode: document.body.classList.contains('nightmode'),
    geoCache: null,
    titoloResolver: null,
    comicNeueRegularB64: null,
    comicNeueBoldB64: null,
    chosen: { genres: [], settingKeys: [] },
    progressReached: 0,
    slowTimer: null,
    textSizeIdx: 1,
    readingMode: false,
    currentAudio: null,
    wakeLock: null,
    pendingSpeech: null,
    speechSequence: 0,
    currentUser: null,
    modalOpener: null,
    installPrompt: null,
};
